# This is a basic workflow to help you get started with Actions

name: Java Compiler

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install software
      run: |
        sudo add-apt-repository ppa:openjdk-r/ppa 
        sudo apt update
        sudo apt install openjdk-8-jdk
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
        java -version      
        ls
      -name: Run Java
       run: javac *.java
       run: java index



