# This is a basic workflow to help you get started with Actions

name: Java Compiler

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
  
    runs-on: ubuntu-latest

  
    steps: 
  
    - uses: actions/checkout@v2

  
    - name: Install software
      run: |
        sudo add-apt-repository ppa:openjdk-r/ppa 
        sudo apt update
        sudo apt install openjdk-8-jdk
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
    - name: Compile
      run: |
        javac index.java
        jar cmf manifest.txt program.jar *.class supports
        mv program.jar bin/program.jar
    - name: Test Jar
      run: java -jar program.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Archive Jar
        run: |
          git status
          git checkout -b working
          git merge master -m "Merge commit"
          git remote add origin https://github.com/samthegitguy/incognow
          git push -u origin master

